### ISSUE TITLE
Rust version?

### ISSUE THREAD

**Issue by sneako** [scylladb/scylla-rust-udf#15]
I am having some trouble using this library so I thought I would try compiling the examples.

[Cargo.toml](https://github.com/scylladb/scylla-rust-udf/blob/main/Cargo.toml#L14) lists `1.66.1`

However, it seems that this project cannot be built with that version:

```shell
❯ rustc --version
rustc 1.66.1 (90743e729 2023-01-10)
❯ cargo --version
cargo 1.66.1 (ad779e08b 2023-01-10)
❯ cargo build
error: package `toml_datetime v0.6.5` cannot be built because it requires rustc 1.67 or newer, while the currently active rustc version is 1.66.1
Either upgrade to rustc 1.67 or newer, or use
cargo update -p toml_datetime@0.6.5 --precise ver
where `ver` is the latest version of `toml_datetime` supporting rustc 1.66.1
```

**Comment by piodul** [comment]
At the moment when `scylla-rust-udf` was released it was possible to compile it with rustc 1.66.1. However, it appears that some dependencies released new versions which have bumped MSRV (many projects do not consider MSRV as a breaking change). Cargo does not take this into consideration when resolving dependencies. Therefore, your options are as what cargo suggests to you:

- Upgrade to Rust 1.67.0 or later,
- or use `cargo update` to request older versions of problematic dependencies in your project's `Cargo.lock`.

**Comment by sneako** [comment]
Thanks! I didn't realize that bumping MSRV was not considered a breaking change. I originally tried compiling with the latest rust version but got errors, so that's why I reverted to the version specified in this project. Maybe there is something wrong in my toolchain... I'll try to create a minimal reproducible example to figure out what is going on here.
