### ISSUE TITLE
Get rid of vendored `scylla-cql` crate

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-rust-udf#5]
Initial version of the library needed some modifications to scylla-cql, so this repo includes a vendored copy of that crate. As far as I know, necessary improvements were already submitted to the upstream scylla-cql and merged. Now, we need to:

1. [x] Verify that scylla-cql's main branch has all of the necessary changes (e.g. submit a PR which does the same as point 3. but with the main branch)
2. [x] Release a new version of scylla-cql (only scylla-cql is necessary, not the whole driver)
3. [x] Submit a PR that gets rid of the vendored scylla-cql and switches to the latest release

**Comment by wmitros** [comment]
I think this is done @piodul ?
